fix regression tests

diff --git a/ksh-20100826-fixregr.patch b/ksh-20100826-fixregr.patch
--- a/ksh-20100826-fixregr.patch
+++ b/ksh-20100826-fixregr.patch
@@ -1,19 +1,23 @@
-diff -up ksh-20101026/src/cmd/ksh93/tests/builtins.sh.fixregr ksh-20101026/src/cmd/ksh93/tests/builtins.sh
---- ksh-20101026/src/cmd/ksh93/tests/builtins.sh.fixregr	2010-10-27 08:52:38.000000000 +0200
-+++ ksh-20101026/src/cmd/ksh93/tests/builtins.sh	2010-11-01 08:49:42.135892758 +0100
-@@ -293,7 +293,7 @@ fi
+diff -up ksh-20101122/src/cmd/ksh93/tests/builtins.sh.fixregr ksh-20101122/src/cmd/ksh93/tests/builtins.sh
+--- ksh-20101122/src/cmd/ksh93/tests/builtins.sh.fixregr	2010-10-27 08:52:38.000000000 +0200
++++ ksh-20101122/src/cmd/ksh93/tests/builtins.sh	2010-11-26 10:17:05.653551931 +0100
+@@ -291,9 +291,9 @@ then	err_exit "printf '%..*s' not workin
+ fi
+ [[ $(printf '%q\n') == '' ]] || err_exit 'printf "%q" with missing arguments'
  # we won't get hit by the one second boundary twice, right?
- [[ $(printf '%T\n' now) == "$(date)" ]] ||
- [[ $(printf '%T\n' now) == "$(date)" ]] ||
+-[[ $(printf '%T\n' now) == "$(date)" ]] ||
+-[[ $(printf '%T\n' now) == "$(date)" ]] ||
 -err_exit 'printf "%T" now'
-+err_exit 'printf "%T" now'"$(printf '%T\n' now) != $(date)"
++[[ $(printf '%T\n' now | sed 's/GMT/UTC/') == "$(date)" ]] ||
++[[ $(printf '%T\n' now | sed 's/GMT/UTC/') == "$(date)" ]] ||
++err_exit 'printf "%T" now = '"$(printf '%T\n' now) != $(date)"
  behead()
  {
  	read line
-diff -up ksh-20101026/src/cmd/ksh93/tests/locale.sh.fixregr ksh-20101026/src/cmd/ksh93/tests/locale.sh
---- ksh-20101026/src/cmd/ksh93/tests/locale.sh.fixregr	2010-10-26 12:12:34.000000000 +0200
-+++ ksh-20101026/src/cmd/ksh93/tests/locale.sh	2010-11-01 09:37:38.719975976 +0100
-@@ -105,6 +105,7 @@ if	(( $($SHELL -c $'export LC_ALL='$loca
+diff -up ksh-20101122/src/cmd/ksh93/tests/locale.sh.fixregr ksh-20101122/src/cmd/ksh93/tests/locale.sh
+--- ksh-20101122/src/cmd/ksh93/tests/locale.sh.fixregr	2010-11-13 01:29:23.000000000 +0100
++++ ksh-20101122/src/cmd/ksh93/tests/locale.sh	2010-11-26 10:08:17.334737934 +0100
+@@ -104,6 +104,7 @@ if	(( $($SHELL -c $'export LC_ALL='$loca
  then	LC_ALL=$locale $SHELL -c b1=$'"\342\202\254\342\202\254\342\202\254\342\202\254w\342\202\254\342\202\254\342\202\254\342\202\254"; [[ ${b1:4:1} == w ]]' || err_exit 'multibyte ${var:offset:len} not working correctly'
  fi
  
@@ -21,7 +25,7 @@ diff -up ksh-20101026/src/cmd/ksh93/tests/locale.sh.fixregr ksh-20101026/src/cmd
  #$SHELL -c 'export LANG='$locale'; printf "\u[20ac]\u[20ac]" > $tmp/two_euro_chars.txt'
  printf $'\342\202\254\342\202\254' > $tmp/two_euro_chars.txt
  exp="6 2 6"
-@@ -112,11 +113,11 @@ set -- $($SHELL -c "
+@@ -111,11 +112,11 @@ set -- $($SHELL -c "
  	unset LC_CTYPE
  	export LANG=$locale
  	export LC_ALL=C
@@ -36,7 +40,7 @@ diff -up ksh-20101026/src/cmd/ksh93/tests/locale.sh.fixregr ksh-20101026/src/cmd
  ")
  got=$*
  [[ $got == $exp ]] || err_exit "command wc LC_ALL default failed -- expected '$exp', got '$got'"
-@@ -135,6 +136,8 @@ set -- $($SHELL -c "
+@@ -134,6 +135,8 @@ set -- $($SHELL -c "
  got=$*
  [[ $got == $exp ]] || err_exit "builtin wc LC_ALL default failed -- expected '$exp', got '$got'"
  
@@ -45,7 +49,7 @@ diff -up ksh-20101026/src/cmd/ksh93/tests/locale.sh.fixregr ksh-20101026/src/cmd
  # multibyte char straddling buffer boundary
  
  {
-@@ -191,6 +194,7 @@ do	exp=$1
+@@ -190,6 +193,7 @@ do	exp=$1
  done
  
  # setocale(LC_ALL,"") after setlocale() initialization
